language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: info@collectorbank.se
  api_key:
    secure: lU5VPfMJkemeTAtgsMdPPqfE75QxezlQhJdZorcaVlPTxbK275xjy91nIvpGqoUrT4w8DwqbhPl4D7NgZZW7yhw70v9AwSsrUcq9+W1PsSyTMOl3OKln8Lr0WugwAVL4lkrahTbn4t4VxhaFvvteNH81pxMIUgW2idgKyTzwFnbChH8w6lQz9RgqnNJA4hw9PogHFNutfvjIz+jGDQXWHhZleQazTKBwTDQe/Ak9fvARMoYYp2n3U6TdsHWB4LBFrVlYW69JNM3e7jHgHsNNedya+bBLsa/5dJZFtC/1+w3zQYa9GvnsIVhnZaUJi8CiuW2LARAE8G1q3e85LXSLHi3xmU4MmLnHc0HODcoXI5ezeXZh7AdT7AUy3OjQhXYefWwxUVkZivug/LKSmRQgFOM1Hi0ZN1TtHJHsH2LgWoOgRgMXOEYM6icyKQD2p21K97lKRPL0/SO2PXU96W+eAR1t0MeDnwR83fXSAb7TXPifr+6P/brx6SaDP8L0/Fs6h5zlLu6JBHzMqu4AwF1UoJTYKKT3XoRionJwzgKWRmfNnwaz9RGnUnVQzAetIa6Q2e+qGUJcjoit3RHp31TovTOk2GI3rtSulkX0fEMWIwPMagbYqDS0j68OVcoUt3RxOpDAWYSSJFofl5V5JYmzOw/f/RP7MFw2rjLYa5iW5Gs=
  on:
    repo: collector-bank/collector-portal-framework
    branch: master
